/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MatchRouteImport } from './routes/match'
import { Route as MessageRouteImport } from './routes/message'
import { Route as MylistRouteImport } from './routes/mylist'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PublishRouteImport } from './routes/publish'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as SearchRouteImport } from './routes/search'
import { Route as WishRouteImport } from './routes/wish'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAuditLogsRouteImport } from './routes/admin.audit-logs'
import { Route as CategoryIndexRouteImport } from './routes/category.index'
import { Route as CategoryCategoryIdRouteImport } from './routes/category.$categoryId'
import { Route as ChatConversationIdRouteImport } from './routes/chat.$conversationId'
import { Route as DetailListingIdRouteImport } from './routes/detail.$listingId'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as ProfileVerificationRouteImport } from './routes/profile.verification'
import { Route as UserUserIdRouteImport } from './routes/user.$userId'
import { Route as WatchersListingIdRouteImport } from './routes/watchers.$listingId'
import { Route as AdminListingsIndexRouteImport } from './routes/admin.listings.index'
import { Route as AdminListingsListingIdRouteImport } from './routes/admin.listings.$listingId'
import { Route as AdminUsersIndexRouteImport } from './routes/admin.users.index'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin.users.$userId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchRoute = MatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => rootRouteImport,
} as any)
const MessageRoute = MessageRouteImport.update({
  id: '/message',
  path: '/message',
  getParentRoute: () => rootRouteImport,
} as any)
const MylistRoute = MylistRouteImport.update({
  id: '/mylist',
  path: '/mylist',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishRoute = PublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const WishRoute = WishRouteImport.update({
  id: '/wish',
  path: '/wish',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminRoute,
} as any)
const CategoryIndexRoute = CategoryIndexRouteImport.update({
  id: '/category/',
  path: '/category/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCategoryIdRoute = CategoryCategoryIdRouteImport.update({
  id: '/category/$categoryId',
  path: '/category/$categoryId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatConversationIdRoute = ChatConversationIdRouteImport.update({
  id: '/chat/$conversationId',
  path: '/chat/$conversationId',
  getParentRoute: () => rootRouteImport,
} as any)
const DetailListingIdRoute = DetailListingIdRouteImport.update({
  id: '/detail/$listingId',
  path: '/detail/$listingId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileVerificationRoute = ProfileVerificationRouteImport.update({
  id: '/profile/verification',
  path: '/profile/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const UserUserIdRoute = UserUserIdRouteImport.update({
  id: '/user/$userId',
  path: '/user/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchersListingIdRoute = WatchersListingIdRouteImport.update({
  id: '/watchers/$listingId',
  path: '/watchers/$listingId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminListingsIndexRoute = AdminListingsIndexRouteImport.update({
  id: '/listings/',
  path: '/listings/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminListingsListingIdRoute = AdminListingsListingIdRouteImport.update({
  id: '/listings/$listingId',
  path: '/listings/$listingId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/match': typeof MatchRoute
  '/message': typeof MessageRoute
  '/mylist': typeof MylistRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/publish': typeof PublishRoute
  '/register': typeof RegisterRoute
  '/scan': typeof ScanRoute
  '/search': typeof SearchRoute
  '/wish': typeof WishRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/category/$categoryId': typeof CategoryCategoryIdRoute
  '/chat/$conversationId': typeof ChatConversationIdRoute
  '/detail/$listingId': typeof DetailListingIdRoute
  '/profile/verification': typeof ProfileVerificationRoute
  '/user/$userId': typeof UserUserIdRoute
  '/watchers/$listingId': typeof WatchersListingIdRoute
  '/admin/': typeof AdminIndexRoute
  '/category/': typeof CategoryIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/admin/listings/$listingId': typeof AdminListingsListingIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/listings/': typeof AdminListingsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/match': typeof MatchRoute
  '/message': typeof MessageRoute
  '/mylist': typeof MylistRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/publish': typeof PublishRoute
  '/register': typeof RegisterRoute
  '/scan': typeof ScanRoute
  '/search': typeof SearchRoute
  '/wish': typeof WishRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/category/$categoryId': typeof CategoryCategoryIdRoute
  '/chat/$conversationId': typeof ChatConversationIdRoute
  '/detail/$listingId': typeof DetailListingIdRoute
  '/profile/verification': typeof ProfileVerificationRoute
  '/user/$userId': typeof UserUserIdRoute
  '/watchers/$listingId': typeof WatchersListingIdRoute
  '/admin': typeof AdminIndexRoute
  '/category': typeof CategoryIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/admin/listings/$listingId': typeof AdminListingsListingIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/listings': typeof AdminListingsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/match': typeof MatchRoute
  '/message': typeof MessageRoute
  '/mylist': typeof MylistRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/publish': typeof PublishRoute
  '/register': typeof RegisterRoute
  '/scan': typeof ScanRoute
  '/search': typeof SearchRoute
  '/wish': typeof WishRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/category/$categoryId': typeof CategoryCategoryIdRoute
  '/chat/$conversationId': typeof ChatConversationIdRoute
  '/detail/$listingId': typeof DetailListingIdRoute
  '/profile/verification': typeof ProfileVerificationRoute
  '/user/$userId': typeof UserUserIdRoute
  '/watchers/$listingId': typeof WatchersListingIdRoute
  '/admin/': typeof AdminIndexRoute
  '/category/': typeof CategoryIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/admin/listings/$listingId': typeof AdminListingsListingIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/listings/': typeof AdminListingsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/match'
    | '/message'
    | '/mylist'
    | '/notifications'
    | '/orders'
    | '/publish'
    | '/register'
    | '/scan'
    | '/search'
    | '/wish'
    | '/admin/audit-logs'
    | '/category/$categoryId'
    | '/chat/$conversationId'
    | '/detail/$listingId'
    | '/profile/verification'
    | '/user/$userId'
    | '/watchers/$listingId'
    | '/admin/'
    | '/category/'
    | '/profile/'
    | '/admin/listings/$listingId'
    | '/admin/users/$userId'
    | '/admin/listings/'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/match'
    | '/message'
    | '/mylist'
    | '/notifications'
    | '/orders'
    | '/publish'
    | '/register'
    | '/scan'
    | '/search'
    | '/wish'
    | '/admin/audit-logs'
    | '/category/$categoryId'
    | '/chat/$conversationId'
    | '/detail/$listingId'
    | '/profile/verification'
    | '/user/$userId'
    | '/watchers/$listingId'
    | '/admin'
    | '/category'
    | '/profile'
    | '/admin/listings/$listingId'
    | '/admin/users/$userId'
    | '/admin/listings'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/match'
    | '/message'
    | '/mylist'
    | '/notifications'
    | '/orders'
    | '/publish'
    | '/register'
    | '/scan'
    | '/search'
    | '/wish'
    | '/admin/audit-logs'
    | '/category/$categoryId'
    | '/chat/$conversationId'
    | '/detail/$listingId'
    | '/profile/verification'
    | '/user/$userId'
    | '/watchers/$listingId'
    | '/admin/'
    | '/category/'
    | '/profile/'
    | '/admin/listings/$listingId'
    | '/admin/users/$userId'
    | '/admin/listings/'
    | '/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  MatchRoute: typeof MatchRoute
  MessageRoute: typeof MessageRoute
  MylistRoute: typeof MylistRoute
  NotificationsRoute: typeof NotificationsRoute
  OrdersRoute: typeof OrdersRoute
  PublishRoute: typeof PublishRoute
  RegisterRoute: typeof RegisterRoute
  ScanRoute: typeof ScanRoute
  SearchRoute: typeof SearchRoute
  WishRoute: typeof WishRoute
  CategoryCategoryIdRoute: typeof CategoryCategoryIdRoute
  ChatConversationIdRoute: typeof ChatConversationIdRoute
  DetailListingIdRoute: typeof DetailListingIdRoute
  ProfileVerificationRoute: typeof ProfileVerificationRoute
  UserUserIdRoute: typeof UserUserIdRoute
  WatchersListingIdRoute: typeof WatchersListingIdRoute
  CategoryIndexRoute: typeof CategoryIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match': {
      id: '/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof MatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/message': {
      id: '/message'
      path: '/message'
      fullPath: '/message'
      preLoaderRoute: typeof MessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mylist': {
      id: '/mylist'
      path: '/mylist'
      fullPath: '/mylist'
      preLoaderRoute: typeof MylistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publish': {
      id: '/publish'
      path: '/publish'
      fullPath: '/publish'
      preLoaderRoute: typeof PublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wish': {
      id: '/wish'
      path: '/wish'
      fullPath: '/wish'
      preLoaderRoute: typeof WishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/category/': {
      id: '/category/'
      path: '/category'
      fullPath: '/category/'
      preLoaderRoute: typeof CategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$categoryId': {
      id: '/category/$categoryId'
      path: '/category/$categoryId'
      fullPath: '/category/$categoryId'
      preLoaderRoute: typeof CategoryCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$conversationId': {
      id: '/chat/$conversationId'
      path: '/chat/$conversationId'
      fullPath: '/chat/$conversationId'
      preLoaderRoute: typeof ChatConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detail/$listingId': {
      id: '/detail/$listingId'
      path: '/detail/$listingId'
      fullPath: '/detail/$listingId'
      preLoaderRoute: typeof DetailListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/verification': {
      id: '/profile/verification'
      path: '/profile/verification'
      fullPath: '/profile/verification'
      preLoaderRoute: typeof ProfileVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$userId': {
      id: '/user/$userId'
      path: '/user/$userId'
      fullPath: '/user/$userId'
      preLoaderRoute: typeof UserUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchers/$listingId': {
      id: '/watchers/$listingId'
      path: '/watchers/$listingId'
      fullPath: '/watchers/$listingId'
      preLoaderRoute: typeof WatchersListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/listings/': {
      id: '/admin/listings/'
      path: '/listings'
      fullPath: '/admin/listings/'
      preLoaderRoute: typeof AdminListingsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/listings/$listingId': {
      id: '/admin/listings/$listingId'
      path: '/listings/$listingId'
      fullPath: '/admin/listings/$listingId'
      preLoaderRoute: typeof AdminListingsListingIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminListingsListingIdRoute: typeof AdminListingsListingIdRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminListingsIndexRoute: typeof AdminListingsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminListingsListingIdRoute: AdminListingsListingIdRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminListingsIndexRoute: AdminListingsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  MatchRoute: MatchRoute,
  MessageRoute: MessageRoute,
  MylistRoute: MylistRoute,
  NotificationsRoute: NotificationsRoute,
  OrdersRoute: OrdersRoute,
  PublishRoute: PublishRoute,
  RegisterRoute: RegisterRoute,
  ScanRoute: ScanRoute,
  SearchRoute: SearchRoute,
  WishRoute: WishRoute,
  CategoryCategoryIdRoute: CategoryCategoryIdRoute,
  ChatConversationIdRoute: ChatConversationIdRoute,
  DetailListingIdRoute: DetailListingIdRoute,
  ProfileVerificationRoute: ProfileVerificationRoute,
  UserUserIdRoute: UserUserIdRoute,
  WatchersListingIdRoute: WatchersListingIdRoute,
  CategoryIndexRoute: CategoryIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
