/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CommentsRouteImport } from './routes/comments'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as FollowingRouteImport } from './routes/following'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MylistRouteImport } from './routes/mylist'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PublishRouteImport } from './routes/publish'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SearchRouteImport } from './routes/search'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as WishRouteImport } from './routes/wish'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminListingsRouteImport } from './routes/admin.listings'
import { Route as AdminMetricsRouteImport } from './routes/admin.metrics'
import { Route as AdminModerationRouteImport } from './routes/admin.moderation'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminTransactionsRouteImport } from './routes/admin.transactions'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as ListingListingIdRouteImport } from './routes/listing.$listingId'
import { Route as MessagesIndexRouteImport } from './routes/messages.index'
import { Route as MessagesConversationIdRouteImport } from './routes/messages.$conversationId'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as OrdersTransactionIdRouteImport } from './routes/orders.$transactionId'
import { Route as UsersUserIdRouteImport } from './routes/users.$userId'
import { Route as WishIndexRouteImport } from './routes/wish.index'
import { Route as WishWishIdRouteImport } from './routes/wish.$wishId'
import { Route as AdminAuditIndexRouteImport } from './routes/admin.audit.index'
import { Route as AdminListingsListingIdRouteImport } from './routes/admin.listings.$listingId'
import { Route as AdminModerationIndexRouteImport } from './routes/admin.moderation.index'
import { Route as AdminModerationRecordIdRouteImport } from './routes/admin.moderation.$recordId'
import { Route as AdminReportsIndexRouteImport } from './routes/admin.reports.index'
import { Route as AdminReportsReportIdRouteImport } from './routes/admin.reports.$reportId'
import { Route as AdminTransactionsIndexRouteImport } from './routes/admin.transactions.index'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin.users.$userId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentsRoute = CommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowingRoute = FollowingRouteImport.update({
  id: '/following',
  path: '/following',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MylistRoute = MylistRouteImport.update({
  id: '/mylist',
  path: '/mylist',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishRoute = PublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const WishRoute = WishRouteImport.update({
  id: '/wish',
  path: '/wish',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminListingsRoute = AdminListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMetricsRoute = AdminMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const ListingListingIdRoute = ListingListingIdRouteImport.update({
  id: '/listing/$listingId',
  path: '/listing/$listingId',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MessagesRoute,
} as any)
const MessagesConversationIdRoute = MessagesConversationIdRouteImport.update({
  id: '/$conversationId',
  path: '/$conversationId',
  getParentRoute: () => MessagesRoute,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrdersRoute,
} as any)
const OrdersTransactionIdRoute = OrdersTransactionIdRouteImport.update({
  id: '/$transactionId',
  path: '/$transactionId',
  getParentRoute: () => OrdersRoute,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const WishIndexRoute = WishIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WishRoute,
} as any)
const WishWishIdRoute = WishWishIdRouteImport.update({
  id: '/$wishId',
  path: '/$wishId',
  getParentRoute: () => WishRoute,
} as any)
const AdminAuditIndexRoute = AdminAuditIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAuditRoute,
} as any)
const AdminListingsListingIdRoute = AdminListingsListingIdRouteImport.update({
  id: '/$listingId',
  path: '/$listingId',
  getParentRoute: () => AdminListingsRoute,
} as any)
const AdminModerationIndexRoute = AdminModerationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminModerationRoute,
} as any)
const AdminModerationRecordIdRoute = AdminModerationRecordIdRouteImport.update({
  id: '/$recordId',
  path: '/$recordId',
  getParentRoute: () => AdminModerationRoute,
} as any)
const AdminReportsIndexRoute = AdminReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminReportsRoute,
} as any)
const AdminReportsReportIdRoute = AdminReportsReportIdRouteImport.update({
  id: '/$reportId',
  path: '/$reportId',
  getParentRoute: () => AdminReportsRoute,
} as any)
const AdminTransactionsIndexRoute = AdminTransactionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminTransactionsRoute,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminUsersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/comments': typeof CommentsRoute
  '/favorites': typeof FavoritesRoute
  '/following': typeof FollowingRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRouteWithChildren
  '/mylist': typeof MylistRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRouteWithChildren
  '/profile': typeof ProfileRoute
  '/publish': typeof PublishRoute
  '/reports': typeof ReportsRoute
  '/search': typeof SearchRoute
  '/verify': typeof VerifyRoute
  '/wish': typeof WishRouteWithChildren
  '/admin/audit': typeof AdminAuditRouteWithChildren
  '/admin/listings': typeof AdminListingsRouteWithChildren
  '/admin/metrics': typeof AdminMetricsRoute
  '/admin/moderation': typeof AdminModerationRouteWithChildren
  '/admin/reports': typeof AdminReportsRouteWithChildren
  '/admin/transactions': typeof AdminTransactionsRouteWithChildren
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/listing/$listingId': typeof ListingListingIdRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/orders/$transactionId': typeof OrdersTransactionIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/wish/$wishId': typeof WishWishIdRoute
  '/admin/': typeof AdminIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/wish/': typeof WishIndexRoute
  '/admin/listings/$listingId': typeof AdminListingsListingIdRoute
  '/admin/moderation/$recordId': typeof AdminModerationRecordIdRoute
  '/admin/reports/$reportId': typeof AdminReportsReportIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/audit/': typeof AdminAuditIndexRoute
  '/admin/moderation/': typeof AdminModerationIndexRoute
  '/admin/reports/': typeof AdminReportsIndexRoute
  '/admin/transactions/': typeof AdminTransactionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comments': typeof CommentsRoute
  '/favorites': typeof FavoritesRoute
  '/following': typeof FollowingRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/mylist': typeof MylistRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/publish': typeof PublishRoute
  '/reports': typeof ReportsRoute
  '/search': typeof SearchRoute
  '/verify': typeof VerifyRoute
  '/admin/listings': typeof AdminListingsRouteWithChildren
  '/admin/metrics': typeof AdminMetricsRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/listing/$listingId': typeof ListingListingIdRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/orders/$transactionId': typeof OrdersTransactionIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/wish/$wishId': typeof WishWishIdRoute
  '/admin': typeof AdminIndexRoute
  '/messages': typeof MessagesIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/wish': typeof WishIndexRoute
  '/admin/listings/$listingId': typeof AdminListingsListingIdRoute
  '/admin/moderation/$recordId': typeof AdminModerationRecordIdRoute
  '/admin/reports/$reportId': typeof AdminReportsReportIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/audit': typeof AdminAuditIndexRoute
  '/admin/moderation': typeof AdminModerationIndexRoute
  '/admin/reports': typeof AdminReportsIndexRoute
  '/admin/transactions': typeof AdminTransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/comments': typeof CommentsRoute
  '/favorites': typeof FavoritesRoute
  '/following': typeof FollowingRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRouteWithChildren
  '/mylist': typeof MylistRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRouteWithChildren
  '/profile': typeof ProfileRoute
  '/publish': typeof PublishRoute
  '/reports': typeof ReportsRoute
  '/search': typeof SearchRoute
  '/verify': typeof VerifyRoute
  '/wish': typeof WishRouteWithChildren
  '/admin/audit': typeof AdminAuditRouteWithChildren
  '/admin/listings': typeof AdminListingsRouteWithChildren
  '/admin/metrics': typeof AdminMetricsRoute
  '/admin/moderation': typeof AdminModerationRouteWithChildren
  '/admin/reports': typeof AdminReportsRouteWithChildren
  '/admin/transactions': typeof AdminTransactionsRouteWithChildren
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/listing/$listingId': typeof ListingListingIdRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/orders/$transactionId': typeof OrdersTransactionIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/wish/$wishId': typeof WishWishIdRoute
  '/admin/': typeof AdminIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/wish/': typeof WishIndexRoute
  '/admin/listings/$listingId': typeof AdminListingsListingIdRoute
  '/admin/moderation/$recordId': typeof AdminModerationRecordIdRoute
  '/admin/reports/$reportId': typeof AdminReportsReportIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/audit/': typeof AdminAuditIndexRoute
  '/admin/moderation/': typeof AdminModerationIndexRoute
  '/admin/reports/': typeof AdminReportsIndexRoute
  '/admin/transactions/': typeof AdminTransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/comments'
    | '/favorites'
    | '/following'
    | '/history'
    | '/login'
    | '/messages'
    | '/mylist'
    | '/notifications'
    | '/orders'
    | '/profile'
    | '/publish'
    | '/reports'
    | '/search'
    | '/verify'
    | '/wish'
    | '/admin/audit'
    | '/admin/listings'
    | '/admin/metrics'
    | '/admin/moderation'
    | '/admin/reports'
    | '/admin/transactions'
    | '/admin/users'
    | '/listing/$listingId'
    | '/messages/$conversationId'
    | '/orders/$transactionId'
    | '/users/$userId'
    | '/wish/$wishId'
    | '/admin/'
    | '/messages/'
    | '/orders/'
    | '/wish/'
    | '/admin/listings/$listingId'
    | '/admin/moderation/$recordId'
    | '/admin/reports/$reportId'
    | '/admin/users/$userId'
    | '/admin/audit/'
    | '/admin/moderation/'
    | '/admin/reports/'
    | '/admin/transactions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/comments'
    | '/favorites'
    | '/following'
    | '/history'
    | '/login'
    | '/mylist'
    | '/notifications'
    | '/profile'
    | '/publish'
    | '/reports'
    | '/search'
    | '/verify'
    | '/admin/listings'
    | '/admin/metrics'
    | '/admin/users'
    | '/listing/$listingId'
    | '/messages/$conversationId'
    | '/orders/$transactionId'
    | '/users/$userId'
    | '/wish/$wishId'
    | '/admin'
    | '/messages'
    | '/orders'
    | '/wish'
    | '/admin/listings/$listingId'
    | '/admin/moderation/$recordId'
    | '/admin/reports/$reportId'
    | '/admin/users/$userId'
    | '/admin/audit'
    | '/admin/moderation'
    | '/admin/reports'
    | '/admin/transactions'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/comments'
    | '/favorites'
    | '/following'
    | '/history'
    | '/login'
    | '/messages'
    | '/mylist'
    | '/notifications'
    | '/orders'
    | '/profile'
    | '/publish'
    | '/reports'
    | '/search'
    | '/verify'
    | '/wish'
    | '/admin/audit'
    | '/admin/listings'
    | '/admin/metrics'
    | '/admin/moderation'
    | '/admin/reports'
    | '/admin/transactions'
    | '/admin/users'
    | '/listing/$listingId'
    | '/messages/$conversationId'
    | '/orders/$transactionId'
    | '/users/$userId'
    | '/wish/$wishId'
    | '/admin/'
    | '/messages/'
    | '/orders/'
    | '/wish/'
    | '/admin/listings/$listingId'
    | '/admin/moderation/$recordId'
    | '/admin/reports/$reportId'
    | '/admin/users/$userId'
    | '/admin/audit/'
    | '/admin/moderation/'
    | '/admin/reports/'
    | '/admin/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CommentsRoute: typeof CommentsRoute
  FavoritesRoute: typeof FavoritesRoute
  FollowingRoute: typeof FollowingRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRouteWithChildren
  MylistRoute: typeof MylistRoute
  NotificationsRoute: typeof NotificationsRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  PublishRoute: typeof PublishRoute
  ReportsRoute: typeof ReportsRoute
  SearchRoute: typeof SearchRoute
  VerifyRoute: typeof VerifyRoute
  WishRoute: typeof WishRouteWithChildren
  ListingListingIdRoute: typeof ListingListingIdRoute
  UsersUserIdRoute: typeof UsersUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comments': {
      id: '/comments'
      path: '/comments'
      fullPath: '/comments'
      preLoaderRoute: typeof CommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/following': {
      id: '/following'
      path: '/following'
      fullPath: '/following'
      preLoaderRoute: typeof FollowingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mylist': {
      id: '/mylist'
      path: '/mylist'
      fullPath: '/mylist'
      preLoaderRoute: typeof MylistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publish': {
      id: '/publish'
      path: '/publish'
      fullPath: '/publish'
      preLoaderRoute: typeof PublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wish': {
      id: '/wish'
      path: '/wish'
      fullPath: '/wish'
      preLoaderRoute: typeof WishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/listings': {
      id: '/admin/listings'
      path: '/listings'
      fullPath: '/admin/listings'
      preLoaderRoute: typeof AdminListingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/metrics': {
      id: '/admin/metrics'
      path: '/metrics'
      fullPath: '/admin/metrics'
      preLoaderRoute: typeof AdminMetricsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/listing/$listingId': {
      id: '/listing/$listingId'
      path: '/listing/$listingId'
      fullPath: '/listing/$listingId'
      preLoaderRoute: typeof ListingListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/messages/$conversationId': {
      id: '/messages/$conversationId'
      path: '/$conversationId'
      fullPath: '/messages/$conversationId'
      preLoaderRoute: typeof MessagesConversationIdRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/orders/': {
      id: '/orders/'
      path: '/'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/orders/$transactionId': {
      id: '/orders/$transactionId'
      path: '/$transactionId'
      fullPath: '/orders/$transactionId'
      preLoaderRoute: typeof OrdersTransactionIdRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wish/': {
      id: '/wish/'
      path: '/'
      fullPath: '/wish/'
      preLoaderRoute: typeof WishIndexRouteImport
      parentRoute: typeof WishRoute
    }
    '/wish/$wishId': {
      id: '/wish/$wishId'
      path: '/$wishId'
      fullPath: '/wish/$wishId'
      preLoaderRoute: typeof WishWishIdRouteImport
      parentRoute: typeof WishRoute
    }
    '/admin/audit/': {
      id: '/admin/audit/'
      path: '/'
      fullPath: '/admin/audit/'
      preLoaderRoute: typeof AdminAuditIndexRouteImport
      parentRoute: typeof AdminAuditRoute
    }
    '/admin/listings/$listingId': {
      id: '/admin/listings/$listingId'
      path: '/$listingId'
      fullPath: '/admin/listings/$listingId'
      preLoaderRoute: typeof AdminListingsListingIdRouteImport
      parentRoute: typeof AdminListingsRoute
    }
    '/admin/moderation/': {
      id: '/admin/moderation/'
      path: '/'
      fullPath: '/admin/moderation/'
      preLoaderRoute: typeof AdminModerationIndexRouteImport
      parentRoute: typeof AdminModerationRoute
    }
    '/admin/moderation/$recordId': {
      id: '/admin/moderation/$recordId'
      path: '/$recordId'
      fullPath: '/admin/moderation/$recordId'
      preLoaderRoute: typeof AdminModerationRecordIdRouteImport
      parentRoute: typeof AdminModerationRoute
    }
    '/admin/reports/': {
      id: '/admin/reports/'
      path: '/'
      fullPath: '/admin/reports/'
      preLoaderRoute: typeof AdminReportsIndexRouteImport
      parentRoute: typeof AdminReportsRoute
    }
    '/admin/reports/$reportId': {
      id: '/admin/reports/$reportId'
      path: '/$reportId'
      fullPath: '/admin/reports/$reportId'
      preLoaderRoute: typeof AdminReportsReportIdRouteImport
      parentRoute: typeof AdminReportsRoute
    }
    '/admin/transactions/': {
      id: '/admin/transactions/'
      path: '/'
      fullPath: '/admin/transactions/'
      preLoaderRoute: typeof AdminTransactionsIndexRouteImport
      parentRoute: typeof AdminTransactionsRoute
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminUsersRoute
    }
  }
}

interface AdminAuditRouteChildren {
  AdminAuditIndexRoute: typeof AdminAuditIndexRoute
}

const AdminAuditRouteChildren: AdminAuditRouteChildren = {
  AdminAuditIndexRoute: AdminAuditIndexRoute,
}

const AdminAuditRouteWithChildren = AdminAuditRoute._addFileChildren(
  AdminAuditRouteChildren,
)

interface AdminListingsRouteChildren {
  AdminListingsListingIdRoute: typeof AdminListingsListingIdRoute
}

const AdminListingsRouteChildren: AdminListingsRouteChildren = {
  AdminListingsListingIdRoute: AdminListingsListingIdRoute,
}

const AdminListingsRouteWithChildren = AdminListingsRoute._addFileChildren(
  AdminListingsRouteChildren,
)

interface AdminModerationRouteChildren {
  AdminModerationRecordIdRoute: typeof AdminModerationRecordIdRoute
  AdminModerationIndexRoute: typeof AdminModerationIndexRoute
}

const AdminModerationRouteChildren: AdminModerationRouteChildren = {
  AdminModerationRecordIdRoute: AdminModerationRecordIdRoute,
  AdminModerationIndexRoute: AdminModerationIndexRoute,
}

const AdminModerationRouteWithChildren = AdminModerationRoute._addFileChildren(
  AdminModerationRouteChildren,
)

interface AdminReportsRouteChildren {
  AdminReportsReportIdRoute: typeof AdminReportsReportIdRoute
  AdminReportsIndexRoute: typeof AdminReportsIndexRoute
}

const AdminReportsRouteChildren: AdminReportsRouteChildren = {
  AdminReportsReportIdRoute: AdminReportsReportIdRoute,
  AdminReportsIndexRoute: AdminReportsIndexRoute,
}

const AdminReportsRouteWithChildren = AdminReportsRoute._addFileChildren(
  AdminReportsRouteChildren,
)

interface AdminTransactionsRouteChildren {
  AdminTransactionsIndexRoute: typeof AdminTransactionsIndexRoute
}

const AdminTransactionsRouteChildren: AdminTransactionsRouteChildren = {
  AdminTransactionsIndexRoute: AdminTransactionsIndexRoute,
}

const AdminTransactionsRouteWithChildren =
  AdminTransactionsRoute._addFileChildren(AdminTransactionsRouteChildren)

interface AdminUsersRouteChildren {
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRouteWithChildren
  AdminListingsRoute: typeof AdminListingsRouteWithChildren
  AdminMetricsRoute: typeof AdminMetricsRoute
  AdminModerationRoute: typeof AdminModerationRouteWithChildren
  AdminReportsRoute: typeof AdminReportsRouteWithChildren
  AdminTransactionsRoute: typeof AdminTransactionsRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRouteWithChildren,
  AdminListingsRoute: AdminListingsRouteWithChildren,
  AdminMetricsRoute: AdminMetricsRoute,
  AdminModerationRoute: AdminModerationRouteWithChildren,
  AdminReportsRoute: AdminReportsRouteWithChildren,
  AdminTransactionsRoute: AdminTransactionsRouteWithChildren,
  AdminUsersRoute: AdminUsersRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MessagesRouteChildren {
  MessagesConversationIdRoute: typeof MessagesConversationIdRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
}

const MessagesRouteChildren: MessagesRouteChildren = {
  MessagesConversationIdRoute: MessagesConversationIdRoute,
  MessagesIndexRoute: MessagesIndexRoute,
}

const MessagesRouteWithChildren = MessagesRoute._addFileChildren(
  MessagesRouteChildren,
)

interface OrdersRouteChildren {
  OrdersTransactionIdRoute: typeof OrdersTransactionIdRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersTransactionIdRoute: OrdersTransactionIdRoute,
  OrdersIndexRoute: OrdersIndexRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

interface WishRouteChildren {
  WishWishIdRoute: typeof WishWishIdRoute
  WishIndexRoute: typeof WishIndexRoute
}

const WishRouteChildren: WishRouteChildren = {
  WishWishIdRoute: WishWishIdRoute,
  WishIndexRoute: WishIndexRoute,
}

const WishRouteWithChildren = WishRoute._addFileChildren(WishRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CommentsRoute: CommentsRoute,
  FavoritesRoute: FavoritesRoute,
  FollowingRoute: FollowingRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRouteWithChildren,
  MylistRoute: MylistRoute,
  NotificationsRoute: NotificationsRoute,
  OrdersRoute: OrdersRouteWithChildren,
  ProfileRoute: ProfileRoute,
  PublishRoute: PublishRoute,
  ReportsRoute: ReportsRoute,
  SearchRoute: SearchRoute,
  VerifyRoute: VerifyRoute,
  WishRoute: WishRouteWithChildren,
  ListingListingIdRoute: ListingListingIdRoute,
  UsersUserIdRoute: UsersUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
